monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.log"
            level: info
